#ifndef COMMON_H
#define COMMON_H

//
#define UPDATE_PERIOD 10
#define MEASUREMENT_PERIOD_USEC 10000
#define CONTROL_PERIOD_USEC 10000
#define OUTPUT_PERIOD_USEC 10000
#define DIAGNOSTIC_PERIOD_MSEC 100
#define MOTOR_NUM 3

// ENCODER POSITION / STATE
#define CURRENT 1
#define PREVIOUS 0
#define VEL_PERIOD 1000

#endif